name: LegendaryShop Premium v1.0
version: 2.6
main: com.trongphu.shopplugin.trongphu
api-version: '1.21'
depend: [Vault]
commands:
  shop:
    description: Lệnh chính mở cửa hàng ảo hoặc quản trị viên.
    usage: /shop [admin/reload]
